/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardWorkforceRouteImport } from './routes/dashboard.workforce'
import { Route as DashboardSimulationRouteImport } from './routes/dashboard.simulation'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardResourceRoutingRouteImport } from './routes/dashboard.resource-routing'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardRecommendationsRouteImport } from './routes/dashboard.recommendations'
import { Route as DashboardPatientFlowRouteImport } from './routes/dashboard.patient-flow'
import { Route as DashboardIntakeRouteImport } from './routes/dashboard.intake'
import { Route as DashboardIcuOperationsRouteImport } from './routes/dashboard.icu-operations'
import { Route as DashboardForecastRouteImport } from './routes/dashboard.forecast'
import { Route as DashboardEquipmentRouteImport } from './routes/dashboard.equipment'
import { Route as DashboardEmergencyRouteImport } from './routes/dashboard.emergency'
import { Route as DashboardEfficiencyRouteImport } from './routes/dashboard.efficiency'
import { Route as DashboardDistrictPredictionsRouteImport } from './routes/dashboard.district-predictions'
import { Route as DashboardDataTransparencyRouteImport } from './routes/dashboard.data-transparency'
import { Route as DashboardCapacityRouteImport } from './routes/dashboard.capacity'
import { Route as DashboardBedAllocationRouteImport } from './routes/dashboard.bed-allocation'
import { Route as DashboardAiTransparencyRouteImport } from './routes/dashboard.ai-transparency'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkforceRoute = DashboardWorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSimulationRoute = DashboardSimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResourceRoutingRoute =
  DashboardResourceRoutingRouteImport.update({
    id: '/resource-routing',
    path: '/resource-routing',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecommendationsRoute =
  DashboardRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPatientFlowRoute = DashboardPatientFlowRouteImport.update({
  id: '/patient-flow',
  path: '/patient-flow',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntakeRoute = DashboardIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIcuOperationsRoute = DashboardIcuOperationsRouteImport.update({
  id: '/icu-operations',
  path: '/icu-operations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardForecastRoute = DashboardForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEquipmentRoute = DashboardEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmergencyRoute = DashboardEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEfficiencyRoute = DashboardEfficiencyRouteImport.update({
  id: '/efficiency',
  path: '/efficiency',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDistrictPredictionsRoute =
  DashboardDistrictPredictionsRouteImport.update({
    id: '/district-predictions',
    path: '/district-predictions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDataTransparencyRoute =
  DashboardDataTransparencyRouteImport.update({
    id: '/data-transparency',
    path: '/data-transparency',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCapacityRoute = DashboardCapacityRouteImport.update({
  id: '/capacity',
  path: '/capacity',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBedAllocationRoute = DashboardBedAllocationRouteImport.update({
  id: '/bed-allocation',
  path: '/bed-allocation',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiTransparencyRoute = DashboardAiTransparencyRouteImport.update({
  id: '/ai-transparency',
  path: '/ai-transparency',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/ai-transparency': typeof DashboardAiTransparencyRoute
  '/dashboard/bed-allocation': typeof DashboardBedAllocationRoute
  '/dashboard/capacity': typeof DashboardCapacityRoute
  '/dashboard/data-transparency': typeof DashboardDataTransparencyRoute
  '/dashboard/district-predictions': typeof DashboardDistrictPredictionsRoute
  '/dashboard/efficiency': typeof DashboardEfficiencyRoute
  '/dashboard/emergency': typeof DashboardEmergencyRoute
  '/dashboard/equipment': typeof DashboardEquipmentRoute
  '/dashboard/forecast': typeof DashboardForecastRoute
  '/dashboard/icu-operations': typeof DashboardIcuOperationsRoute
  '/dashboard/intake': typeof DashboardIntakeRoute
  '/dashboard/patient-flow': typeof DashboardPatientFlowRoute
  '/dashboard/recommendations': typeof DashboardRecommendationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/resource-routing': typeof DashboardResourceRoutingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/simulation': typeof DashboardSimulationRoute
  '/dashboard/workforce': typeof DashboardWorkforceRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/ai-transparency': typeof DashboardAiTransparencyRoute
  '/dashboard/bed-allocation': typeof DashboardBedAllocationRoute
  '/dashboard/capacity': typeof DashboardCapacityRoute
  '/dashboard/data-transparency': typeof DashboardDataTransparencyRoute
  '/dashboard/district-predictions': typeof DashboardDistrictPredictionsRoute
  '/dashboard/efficiency': typeof DashboardEfficiencyRoute
  '/dashboard/emergency': typeof DashboardEmergencyRoute
  '/dashboard/equipment': typeof DashboardEquipmentRoute
  '/dashboard/forecast': typeof DashboardForecastRoute
  '/dashboard/icu-operations': typeof DashboardIcuOperationsRoute
  '/dashboard/intake': typeof DashboardIntakeRoute
  '/dashboard/patient-flow': typeof DashboardPatientFlowRoute
  '/dashboard/recommendations': typeof DashboardRecommendationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/resource-routing': typeof DashboardResourceRoutingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/simulation': typeof DashboardSimulationRoute
  '/dashboard/workforce': typeof DashboardWorkforceRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/ai-transparency': typeof DashboardAiTransparencyRoute
  '/dashboard/bed-allocation': typeof DashboardBedAllocationRoute
  '/dashboard/capacity': typeof DashboardCapacityRoute
  '/dashboard/data-transparency': typeof DashboardDataTransparencyRoute
  '/dashboard/district-predictions': typeof DashboardDistrictPredictionsRoute
  '/dashboard/efficiency': typeof DashboardEfficiencyRoute
  '/dashboard/emergency': typeof DashboardEmergencyRoute
  '/dashboard/equipment': typeof DashboardEquipmentRoute
  '/dashboard/forecast': typeof DashboardForecastRoute
  '/dashboard/icu-operations': typeof DashboardIcuOperationsRoute
  '/dashboard/intake': typeof DashboardIntakeRoute
  '/dashboard/patient-flow': typeof DashboardPatientFlowRoute
  '/dashboard/recommendations': typeof DashboardRecommendationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/resource-routing': typeof DashboardResourceRoutingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/simulation': typeof DashboardSimulationRoute
  '/dashboard/workforce': typeof DashboardWorkforceRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/ai-transparency'
    | '/dashboard/bed-allocation'
    | '/dashboard/capacity'
    | '/dashboard/data-transparency'
    | '/dashboard/district-predictions'
    | '/dashboard/efficiency'
    | '/dashboard/emergency'
    | '/dashboard/equipment'
    | '/dashboard/forecast'
    | '/dashboard/icu-operations'
    | '/dashboard/intake'
    | '/dashboard/patient-flow'
    | '/dashboard/recommendations'
    | '/dashboard/reports'
    | '/dashboard/resource-routing'
    | '/dashboard/settings'
    | '/dashboard/simulation'
    | '/dashboard/workforce'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/admin'
    | '/dashboard/ai-transparency'
    | '/dashboard/bed-allocation'
    | '/dashboard/capacity'
    | '/dashboard/data-transparency'
    | '/dashboard/district-predictions'
    | '/dashboard/efficiency'
    | '/dashboard/emergency'
    | '/dashboard/equipment'
    | '/dashboard/forecast'
    | '/dashboard/icu-operations'
    | '/dashboard/intake'
    | '/dashboard/patient-flow'
    | '/dashboard/recommendations'
    | '/dashboard/reports'
    | '/dashboard/resource-routing'
    | '/dashboard/settings'
    | '/dashboard/simulation'
    | '/dashboard/workforce'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/ai-transparency'
    | '/dashboard/bed-allocation'
    | '/dashboard/capacity'
    | '/dashboard/data-transparency'
    | '/dashboard/district-predictions'
    | '/dashboard/efficiency'
    | '/dashboard/emergency'
    | '/dashboard/equipment'
    | '/dashboard/forecast'
    | '/dashboard/icu-operations'
    | '/dashboard/intake'
    | '/dashboard/patient-flow'
    | '/dashboard/recommendations'
    | '/dashboard/reports'
    | '/dashboard/resource-routing'
    | '/dashboard/settings'
    | '/dashboard/simulation'
    | '/dashboard/workforce'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workforce': {
      id: '/dashboard/workforce'
      path: '/workforce'
      fullPath: '/dashboard/workforce'
      preLoaderRoute: typeof DashboardWorkforceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/simulation': {
      id: '/dashboard/simulation'
      path: '/simulation'
      fullPath: '/dashboard/simulation'
      preLoaderRoute: typeof DashboardSimulationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resource-routing': {
      id: '/dashboard/resource-routing'
      path: '/resource-routing'
      fullPath: '/dashboard/resource-routing'
      preLoaderRoute: typeof DashboardResourceRoutingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/recommendations': {
      id: '/dashboard/recommendations'
      path: '/recommendations'
      fullPath: '/dashboard/recommendations'
      preLoaderRoute: typeof DashboardRecommendationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patient-flow': {
      id: '/dashboard/patient-flow'
      path: '/patient-flow'
      fullPath: '/dashboard/patient-flow'
      preLoaderRoute: typeof DashboardPatientFlowRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/intake': {
      id: '/dashboard/intake'
      path: '/intake'
      fullPath: '/dashboard/intake'
      preLoaderRoute: typeof DashboardIntakeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/icu-operations': {
      id: '/dashboard/icu-operations'
      path: '/icu-operations'
      fullPath: '/dashboard/icu-operations'
      preLoaderRoute: typeof DashboardIcuOperationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/forecast': {
      id: '/dashboard/forecast'
      path: '/forecast'
      fullPath: '/dashboard/forecast'
      preLoaderRoute: typeof DashboardForecastRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/equipment': {
      id: '/dashboard/equipment'
      path: '/equipment'
      fullPath: '/dashboard/equipment'
      preLoaderRoute: typeof DashboardEquipmentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/emergency': {
      id: '/dashboard/emergency'
      path: '/emergency'
      fullPath: '/dashboard/emergency'
      preLoaderRoute: typeof DashboardEmergencyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/efficiency': {
      id: '/dashboard/efficiency'
      path: '/efficiency'
      fullPath: '/dashboard/efficiency'
      preLoaderRoute: typeof DashboardEfficiencyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/district-predictions': {
      id: '/dashboard/district-predictions'
      path: '/district-predictions'
      fullPath: '/dashboard/district-predictions'
      preLoaderRoute: typeof DashboardDistrictPredictionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/data-transparency': {
      id: '/dashboard/data-transparency'
      path: '/data-transparency'
      fullPath: '/dashboard/data-transparency'
      preLoaderRoute: typeof DashboardDataTransparencyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/capacity': {
      id: '/dashboard/capacity'
      path: '/capacity'
      fullPath: '/dashboard/capacity'
      preLoaderRoute: typeof DashboardCapacityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bed-allocation': {
      id: '/dashboard/bed-allocation'
      path: '/bed-allocation'
      fullPath: '/dashboard/bed-allocation'
      preLoaderRoute: typeof DashboardBedAllocationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-transparency': {
      id: '/dashboard/ai-transparency'
      path: '/ai-transparency'
      fullPath: '/dashboard/ai-transparency'
      preLoaderRoute: typeof DashboardAiTransparencyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAiTransparencyRoute: typeof DashboardAiTransparencyRoute
  DashboardBedAllocationRoute: typeof DashboardBedAllocationRoute
  DashboardCapacityRoute: typeof DashboardCapacityRoute
  DashboardDataTransparencyRoute: typeof DashboardDataTransparencyRoute
  DashboardDistrictPredictionsRoute: typeof DashboardDistrictPredictionsRoute
  DashboardEfficiencyRoute: typeof DashboardEfficiencyRoute
  DashboardEmergencyRoute: typeof DashboardEmergencyRoute
  DashboardEquipmentRoute: typeof DashboardEquipmentRoute
  DashboardForecastRoute: typeof DashboardForecastRoute
  DashboardIcuOperationsRoute: typeof DashboardIcuOperationsRoute
  DashboardIntakeRoute: typeof DashboardIntakeRoute
  DashboardPatientFlowRoute: typeof DashboardPatientFlowRoute
  DashboardRecommendationsRoute: typeof DashboardRecommendationsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardResourceRoutingRoute: typeof DashboardResourceRoutingRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSimulationRoute: typeof DashboardSimulationRoute
  DashboardWorkforceRoute: typeof DashboardWorkforceRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAiTransparencyRoute: DashboardAiTransparencyRoute,
  DashboardBedAllocationRoute: DashboardBedAllocationRoute,
  DashboardCapacityRoute: DashboardCapacityRoute,
  DashboardDataTransparencyRoute: DashboardDataTransparencyRoute,
  DashboardDistrictPredictionsRoute: DashboardDistrictPredictionsRoute,
  DashboardEfficiencyRoute: DashboardEfficiencyRoute,
  DashboardEmergencyRoute: DashboardEmergencyRoute,
  DashboardEquipmentRoute: DashboardEquipmentRoute,
  DashboardForecastRoute: DashboardForecastRoute,
  DashboardIcuOperationsRoute: DashboardIcuOperationsRoute,
  DashboardIntakeRoute: DashboardIntakeRoute,
  DashboardPatientFlowRoute: DashboardPatientFlowRoute,
  DashboardRecommendationsRoute: DashboardRecommendationsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardResourceRoutingRoute: DashboardResourceRoutingRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSimulationRoute: DashboardSimulationRoute,
  DashboardWorkforceRoute: DashboardWorkforceRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
