/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HospitalRouteImport } from './routes/hospital'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HospitalIndexRouteImport } from './routes/hospital.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as HospitalStaffRouteImport } from './routes/hospital.staff'
import { Route as HospitalSignupRouteImport } from './routes/hospital.signup'
import { Route as HospitalSettingsRouteImport } from './routes/hospital.settings'
import { Route as HospitalReportsRouteImport } from './routes/hospital.reports'
import { Route as HospitalPatientsRouteImport } from './routes/hospital.patients'
import { Route as HospitalOnboardingRouteImport } from './routes/hospital.onboarding'
import { Route as HospitalLoginRouteImport } from './routes/hospital.login'
import { Route as HospitalLearningRouteImport } from './routes/hospital.learning'
import { Route as HospitalIcuRouteImport } from './routes/hospital.icu'
import { Route as HospitalHistoryRouteImport } from './routes/hospital.history'
import { Route as HospitalForgotPasswordRouteImport } from './routes/hospital.forgot-password'
import { Route as HospitalEquipmentRouteImport } from './routes/hospital.equipment'
import { Route as HospitalDataRouteImport } from './routes/hospital.data'
import { Route as HospitalBedsRouteImport } from './routes/hospital.beds'
import { Route as HospitalAutomationRouteImport } from './routes/hospital.automation'
import { Route as HospitalAnalyticsRouteImport } from './routes/hospital.analytics'
import { Route as HospitalAlertsRouteImport } from './routes/hospital.alerts'
import { Route as DashboardWorkforceRouteImport } from './routes/dashboard.workforce'
import { Route as DashboardTwinRouteImport } from './routes/dashboard.twin'
import { Route as DashboardSimulationRouteImport } from './routes/dashboard.simulation'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardResourceRoutingRouteImport } from './routes/dashboard.resource-routing'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardRecommendationsRouteImport } from './routes/dashboard.recommendations'
import { Route as DashboardPatientFlowRouteImport } from './routes/dashboard.patient-flow'
import { Route as DashboardIntakeRouteImport } from './routes/dashboard.intake'
import { Route as DashboardImpactRouteImport } from './routes/dashboard.impact'
import { Route as DashboardIcuOperationsRouteImport } from './routes/dashboard.icu-operations'
import { Route as DashboardForecastRouteImport } from './routes/dashboard.forecast'
import { Route as DashboardEquipmentRouteImport } from './routes/dashboard.equipment'
import { Route as DashboardEmergencyRouteImport } from './routes/dashboard.emergency'
import { Route as DashboardEfficiencyRouteImport } from './routes/dashboard.efficiency'
import { Route as DashboardDistrictPredictionsRouteImport } from './routes/dashboard.district-predictions'
import { Route as DashboardDataTransparencyRouteImport } from './routes/dashboard.data-transparency'
import { Route as DashboardCrisisRouteImport } from './routes/dashboard.crisis'
import { Route as DashboardCapacityRouteImport } from './routes/dashboard.capacity'
import { Route as DashboardBedAllocationRouteImport } from './routes/dashboard.bed-allocation'
import { Route as DashboardAiTransparencyRouteImport } from './routes/dashboard.ai-transparency'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'

const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalRoute = HospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalIndexRoute = HospitalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HospitalRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const HospitalStaffRoute = HospitalStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalSignupRoute = HospitalSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalSettingsRoute = HospitalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalReportsRoute = HospitalReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalPatientsRoute = HospitalPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalOnboardingRoute = HospitalOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalLoginRoute = HospitalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalLearningRoute = HospitalLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalIcuRoute = HospitalIcuRouteImport.update({
  id: '/icu',
  path: '/icu',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalHistoryRoute = HospitalHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalForgotPasswordRoute = HospitalForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalEquipmentRoute = HospitalEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalDataRoute = HospitalDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalBedsRoute = HospitalBedsRouteImport.update({
  id: '/beds',
  path: '/beds',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalAutomationRoute = HospitalAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalAnalyticsRoute = HospitalAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalAlertsRoute = HospitalAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => HospitalRoute,
} as any)
const DashboardWorkforceRoute = DashboardWorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTwinRoute = DashboardTwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSimulationRoute = DashboardSimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResourceRoutingRoute =
  DashboardResourceRoutingRouteImport.update({
    id: '/resource-routing',
    path: '/resource-routing',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecommendationsRoute =
  DashboardRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPatientFlowRoute = DashboardPatientFlowRouteImport.update({
  id: '/patient-flow',
  path: '/patient-flow',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntakeRoute = DashboardIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImpactRoute = DashboardImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIcuOperationsRoute = DashboardIcuOperationsRouteImport.update({
  id: '/icu-operations',
  path: '/icu-operations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardForecastRoute = DashboardForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEquipmentRoute = DashboardEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmergencyRoute = DashboardEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEfficiencyRoute = DashboardEfficiencyRouteImport.update({
  id: '/efficiency',
  path: '/efficiency',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDistrictPredictionsRoute =
  DashboardDistrictPredictionsRouteImport.update({
    id: '/district-predictions',
    path: '/district-predictions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDataTransparencyRoute =
  DashboardDataTransparencyRouteImport.update({
    id: '/data-transparency',
    path: '/data-transparency',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCrisisRoute = DashboardCrisisRouteImport.update({
  id: '/crisis',
  path: '/crisis',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCapacityRoute = DashboardCapacityRouteImport.update({
  id: '/capacity',
  path: '/capacity',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBedAllocationRoute = DashboardBedAllocationRouteImport.update({
  id: '/bed-allocation',
  path: '/bed-allocation',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiTransparencyRoute = DashboardAiTransparencyRouteImport.update({
  id: '/ai-transparency',
  path: '/ai-transparency',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/hospital': typeof HospitalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/ai-transparency': typeof DashboardAiTransparencyRoute
  '/dashboard/bed-allocation': typeof DashboardBedAllocationRoute
  '/dashboard/capacity': typeof DashboardCapacityRoute
  '/dashboard/crisis': typeof DashboardCrisisRoute
  '/dashboard/data-transparency': typeof DashboardDataTransparencyRoute
  '/dashboard/district-predictions': typeof DashboardDistrictPredictionsRoute
  '/dashboard/efficiency': typeof DashboardEfficiencyRoute
  '/dashboard/emergency': typeof DashboardEmergencyRoute
  '/dashboard/equipment': typeof DashboardEquipmentRoute
  '/dashboard/forecast': typeof DashboardForecastRoute
  '/dashboard/icu-operations': typeof DashboardIcuOperationsRoute
  '/dashboard/impact': typeof DashboardImpactRoute
  '/dashboard/intake': typeof DashboardIntakeRoute
  '/dashboard/patient-flow': typeof DashboardPatientFlowRoute
  '/dashboard/recommendations': typeof DashboardRecommendationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/resource-routing': typeof DashboardResourceRoutingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/simulation': typeof DashboardSimulationRoute
  '/dashboard/twin': typeof DashboardTwinRoute
  '/dashboard/workforce': typeof DashboardWorkforceRoute
  '/hospital/alerts': typeof HospitalAlertsRoute
  '/hospital/analytics': typeof HospitalAnalyticsRoute
  '/hospital/automation': typeof HospitalAutomationRoute
  '/hospital/beds': typeof HospitalBedsRoute
  '/hospital/data': typeof HospitalDataRoute
  '/hospital/equipment': typeof HospitalEquipmentRoute
  '/hospital/forgot-password': typeof HospitalForgotPasswordRoute
  '/hospital/history': typeof HospitalHistoryRoute
  '/hospital/icu': typeof HospitalIcuRoute
  '/hospital/learning': typeof HospitalLearningRoute
  '/hospital/login': typeof HospitalLoginRoute
  '/hospital/onboarding': typeof HospitalOnboardingRoute
  '/hospital/patients': typeof HospitalPatientsRoute
  '/hospital/reports': typeof HospitalReportsRoute
  '/hospital/settings': typeof HospitalSettingsRoute
  '/hospital/signup': typeof HospitalSignupRoute
  '/hospital/staff': typeof HospitalStaffRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/hospital/': typeof HospitalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/ai-transparency': typeof DashboardAiTransparencyRoute
  '/dashboard/bed-allocation': typeof DashboardBedAllocationRoute
  '/dashboard/capacity': typeof DashboardCapacityRoute
  '/dashboard/crisis': typeof DashboardCrisisRoute
  '/dashboard/data-transparency': typeof DashboardDataTransparencyRoute
  '/dashboard/district-predictions': typeof DashboardDistrictPredictionsRoute
  '/dashboard/efficiency': typeof DashboardEfficiencyRoute
  '/dashboard/emergency': typeof DashboardEmergencyRoute
  '/dashboard/equipment': typeof DashboardEquipmentRoute
  '/dashboard/forecast': typeof DashboardForecastRoute
  '/dashboard/icu-operations': typeof DashboardIcuOperationsRoute
  '/dashboard/impact': typeof DashboardImpactRoute
  '/dashboard/intake': typeof DashboardIntakeRoute
  '/dashboard/patient-flow': typeof DashboardPatientFlowRoute
  '/dashboard/recommendations': typeof DashboardRecommendationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/resource-routing': typeof DashboardResourceRoutingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/simulation': typeof DashboardSimulationRoute
  '/dashboard/twin': typeof DashboardTwinRoute
  '/dashboard/workforce': typeof DashboardWorkforceRoute
  '/hospital/alerts': typeof HospitalAlertsRoute
  '/hospital/analytics': typeof HospitalAnalyticsRoute
  '/hospital/automation': typeof HospitalAutomationRoute
  '/hospital/beds': typeof HospitalBedsRoute
  '/hospital/data': typeof HospitalDataRoute
  '/hospital/equipment': typeof HospitalEquipmentRoute
  '/hospital/forgot-password': typeof HospitalForgotPasswordRoute
  '/hospital/history': typeof HospitalHistoryRoute
  '/hospital/icu': typeof HospitalIcuRoute
  '/hospital/learning': typeof HospitalLearningRoute
  '/hospital/login': typeof HospitalLoginRoute
  '/hospital/onboarding': typeof HospitalOnboardingRoute
  '/hospital/patients': typeof HospitalPatientsRoute
  '/hospital/reports': typeof HospitalReportsRoute
  '/hospital/settings': typeof HospitalSettingsRoute
  '/hospital/signup': typeof HospitalSignupRoute
  '/hospital/staff': typeof HospitalStaffRoute
  '/dashboard': typeof DashboardIndexRoute
  '/hospital': typeof HospitalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/hospital': typeof HospitalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/ai-transparency': typeof DashboardAiTransparencyRoute
  '/dashboard/bed-allocation': typeof DashboardBedAllocationRoute
  '/dashboard/capacity': typeof DashboardCapacityRoute
  '/dashboard/crisis': typeof DashboardCrisisRoute
  '/dashboard/data-transparency': typeof DashboardDataTransparencyRoute
  '/dashboard/district-predictions': typeof DashboardDistrictPredictionsRoute
  '/dashboard/efficiency': typeof DashboardEfficiencyRoute
  '/dashboard/emergency': typeof DashboardEmergencyRoute
  '/dashboard/equipment': typeof DashboardEquipmentRoute
  '/dashboard/forecast': typeof DashboardForecastRoute
  '/dashboard/icu-operations': typeof DashboardIcuOperationsRoute
  '/dashboard/impact': typeof DashboardImpactRoute
  '/dashboard/intake': typeof DashboardIntakeRoute
  '/dashboard/patient-flow': typeof DashboardPatientFlowRoute
  '/dashboard/recommendations': typeof DashboardRecommendationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/resource-routing': typeof DashboardResourceRoutingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/simulation': typeof DashboardSimulationRoute
  '/dashboard/twin': typeof DashboardTwinRoute
  '/dashboard/workforce': typeof DashboardWorkforceRoute
  '/hospital/alerts': typeof HospitalAlertsRoute
  '/hospital/analytics': typeof HospitalAnalyticsRoute
  '/hospital/automation': typeof HospitalAutomationRoute
  '/hospital/beds': typeof HospitalBedsRoute
  '/hospital/data': typeof HospitalDataRoute
  '/hospital/equipment': typeof HospitalEquipmentRoute
  '/hospital/forgot-password': typeof HospitalForgotPasswordRoute
  '/hospital/history': typeof HospitalHistoryRoute
  '/hospital/icu': typeof HospitalIcuRoute
  '/hospital/learning': typeof HospitalLearningRoute
  '/hospital/login': typeof HospitalLoginRoute
  '/hospital/onboarding': typeof HospitalOnboardingRoute
  '/hospital/patients': typeof HospitalPatientsRoute
  '/hospital/reports': typeof HospitalReportsRoute
  '/hospital/settings': typeof HospitalSettingsRoute
  '/hospital/signup': typeof HospitalSignupRoute
  '/hospital/staff': typeof HospitalStaffRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/hospital/': typeof HospitalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/hospital'
    | '/pricing'
    | '/security'
    | '/dashboard/admin'
    | '/dashboard/ai-transparency'
    | '/dashboard/bed-allocation'
    | '/dashboard/capacity'
    | '/dashboard/crisis'
    | '/dashboard/data-transparency'
    | '/dashboard/district-predictions'
    | '/dashboard/efficiency'
    | '/dashboard/emergency'
    | '/dashboard/equipment'
    | '/dashboard/forecast'
    | '/dashboard/icu-operations'
    | '/dashboard/impact'
    | '/dashboard/intake'
    | '/dashboard/patient-flow'
    | '/dashboard/recommendations'
    | '/dashboard/reports'
    | '/dashboard/resource-routing'
    | '/dashboard/settings'
    | '/dashboard/simulation'
    | '/dashboard/twin'
    | '/dashboard/workforce'
    | '/hospital/alerts'
    | '/hospital/analytics'
    | '/hospital/automation'
    | '/hospital/beds'
    | '/hospital/data'
    | '/hospital/equipment'
    | '/hospital/forgot-password'
    | '/hospital/history'
    | '/hospital/icu'
    | '/hospital/learning'
    | '/hospital/login'
    | '/hospital/onboarding'
    | '/hospital/patients'
    | '/hospital/reports'
    | '/hospital/settings'
    | '/hospital/signup'
    | '/hospital/staff'
    | '/dashboard/'
    | '/hospital/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/security'
    | '/dashboard/admin'
    | '/dashboard/ai-transparency'
    | '/dashboard/bed-allocation'
    | '/dashboard/capacity'
    | '/dashboard/crisis'
    | '/dashboard/data-transparency'
    | '/dashboard/district-predictions'
    | '/dashboard/efficiency'
    | '/dashboard/emergency'
    | '/dashboard/equipment'
    | '/dashboard/forecast'
    | '/dashboard/icu-operations'
    | '/dashboard/impact'
    | '/dashboard/intake'
    | '/dashboard/patient-flow'
    | '/dashboard/recommendations'
    | '/dashboard/reports'
    | '/dashboard/resource-routing'
    | '/dashboard/settings'
    | '/dashboard/simulation'
    | '/dashboard/twin'
    | '/dashboard/workforce'
    | '/hospital/alerts'
    | '/hospital/analytics'
    | '/hospital/automation'
    | '/hospital/beds'
    | '/hospital/data'
    | '/hospital/equipment'
    | '/hospital/forgot-password'
    | '/hospital/history'
    | '/hospital/icu'
    | '/hospital/learning'
    | '/hospital/login'
    | '/hospital/onboarding'
    | '/hospital/patients'
    | '/hospital/reports'
    | '/hospital/settings'
    | '/hospital/signup'
    | '/hospital/staff'
    | '/dashboard'
    | '/hospital'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/hospital'
    | '/pricing'
    | '/security'
    | '/dashboard/admin'
    | '/dashboard/ai-transparency'
    | '/dashboard/bed-allocation'
    | '/dashboard/capacity'
    | '/dashboard/crisis'
    | '/dashboard/data-transparency'
    | '/dashboard/district-predictions'
    | '/dashboard/efficiency'
    | '/dashboard/emergency'
    | '/dashboard/equipment'
    | '/dashboard/forecast'
    | '/dashboard/icu-operations'
    | '/dashboard/impact'
    | '/dashboard/intake'
    | '/dashboard/patient-flow'
    | '/dashboard/recommendations'
    | '/dashboard/reports'
    | '/dashboard/resource-routing'
    | '/dashboard/settings'
    | '/dashboard/simulation'
    | '/dashboard/twin'
    | '/dashboard/workforce'
    | '/hospital/alerts'
    | '/hospital/analytics'
    | '/hospital/automation'
    | '/hospital/beds'
    | '/hospital/data'
    | '/hospital/equipment'
    | '/hospital/forgot-password'
    | '/hospital/history'
    | '/hospital/icu'
    | '/hospital/learning'
    | '/hospital/login'
    | '/hospital/onboarding'
    | '/hospital/patients'
    | '/hospital/reports'
    | '/hospital/settings'
    | '/hospital/signup'
    | '/hospital/staff'
    | '/dashboard/'
    | '/hospital/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  HospitalRoute: typeof HospitalRouteWithChildren
  PricingRoute: typeof PricingRoute
  SecurityRoute: typeof SecurityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital': {
      id: '/hospital'
      path: '/hospital'
      fullPath: '/hospital'
      preLoaderRoute: typeof HospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/': {
      id: '/hospital/'
      path: '/'
      fullPath: '/hospital/'
      preLoaderRoute: typeof HospitalIndexRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/hospital/staff': {
      id: '/hospital/staff'
      path: '/staff'
      fullPath: '/hospital/staff'
      preLoaderRoute: typeof HospitalStaffRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/signup': {
      id: '/hospital/signup'
      path: '/signup'
      fullPath: '/hospital/signup'
      preLoaderRoute: typeof HospitalSignupRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/settings': {
      id: '/hospital/settings'
      path: '/settings'
      fullPath: '/hospital/settings'
      preLoaderRoute: typeof HospitalSettingsRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/reports': {
      id: '/hospital/reports'
      path: '/reports'
      fullPath: '/hospital/reports'
      preLoaderRoute: typeof HospitalReportsRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/patients': {
      id: '/hospital/patients'
      path: '/patients'
      fullPath: '/hospital/patients'
      preLoaderRoute: typeof HospitalPatientsRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/onboarding': {
      id: '/hospital/onboarding'
      path: '/onboarding'
      fullPath: '/hospital/onboarding'
      preLoaderRoute: typeof HospitalOnboardingRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/login': {
      id: '/hospital/login'
      path: '/login'
      fullPath: '/hospital/login'
      preLoaderRoute: typeof HospitalLoginRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/learning': {
      id: '/hospital/learning'
      path: '/learning'
      fullPath: '/hospital/learning'
      preLoaderRoute: typeof HospitalLearningRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/icu': {
      id: '/hospital/icu'
      path: '/icu'
      fullPath: '/hospital/icu'
      preLoaderRoute: typeof HospitalIcuRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/history': {
      id: '/hospital/history'
      path: '/history'
      fullPath: '/hospital/history'
      preLoaderRoute: typeof HospitalHistoryRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/forgot-password': {
      id: '/hospital/forgot-password'
      path: '/forgot-password'
      fullPath: '/hospital/forgot-password'
      preLoaderRoute: typeof HospitalForgotPasswordRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/equipment': {
      id: '/hospital/equipment'
      path: '/equipment'
      fullPath: '/hospital/equipment'
      preLoaderRoute: typeof HospitalEquipmentRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/data': {
      id: '/hospital/data'
      path: '/data'
      fullPath: '/hospital/data'
      preLoaderRoute: typeof HospitalDataRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/beds': {
      id: '/hospital/beds'
      path: '/beds'
      fullPath: '/hospital/beds'
      preLoaderRoute: typeof HospitalBedsRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/automation': {
      id: '/hospital/automation'
      path: '/automation'
      fullPath: '/hospital/automation'
      preLoaderRoute: typeof HospitalAutomationRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/analytics': {
      id: '/hospital/analytics'
      path: '/analytics'
      fullPath: '/hospital/analytics'
      preLoaderRoute: typeof HospitalAnalyticsRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/alerts': {
      id: '/hospital/alerts'
      path: '/alerts'
      fullPath: '/hospital/alerts'
      preLoaderRoute: typeof HospitalAlertsRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/dashboard/workforce': {
      id: '/dashboard/workforce'
      path: '/workforce'
      fullPath: '/dashboard/workforce'
      preLoaderRoute: typeof DashboardWorkforceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/twin': {
      id: '/dashboard/twin'
      path: '/twin'
      fullPath: '/dashboard/twin'
      preLoaderRoute: typeof DashboardTwinRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/simulation': {
      id: '/dashboard/simulation'
      path: '/simulation'
      fullPath: '/dashboard/simulation'
      preLoaderRoute: typeof DashboardSimulationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resource-routing': {
      id: '/dashboard/resource-routing'
      path: '/resource-routing'
      fullPath: '/dashboard/resource-routing'
      preLoaderRoute: typeof DashboardResourceRoutingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/recommendations': {
      id: '/dashboard/recommendations'
      path: '/recommendations'
      fullPath: '/dashboard/recommendations'
      preLoaderRoute: typeof DashboardRecommendationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patient-flow': {
      id: '/dashboard/patient-flow'
      path: '/patient-flow'
      fullPath: '/dashboard/patient-flow'
      preLoaderRoute: typeof DashboardPatientFlowRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/intake': {
      id: '/dashboard/intake'
      path: '/intake'
      fullPath: '/dashboard/intake'
      preLoaderRoute: typeof DashboardIntakeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/impact': {
      id: '/dashboard/impact'
      path: '/impact'
      fullPath: '/dashboard/impact'
      preLoaderRoute: typeof DashboardImpactRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/icu-operations': {
      id: '/dashboard/icu-operations'
      path: '/icu-operations'
      fullPath: '/dashboard/icu-operations'
      preLoaderRoute: typeof DashboardIcuOperationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/forecast': {
      id: '/dashboard/forecast'
      path: '/forecast'
      fullPath: '/dashboard/forecast'
      preLoaderRoute: typeof DashboardForecastRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/equipment': {
      id: '/dashboard/equipment'
      path: '/equipment'
      fullPath: '/dashboard/equipment'
      preLoaderRoute: typeof DashboardEquipmentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/emergency': {
      id: '/dashboard/emergency'
      path: '/emergency'
      fullPath: '/dashboard/emergency'
      preLoaderRoute: typeof DashboardEmergencyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/efficiency': {
      id: '/dashboard/efficiency'
      path: '/efficiency'
      fullPath: '/dashboard/efficiency'
      preLoaderRoute: typeof DashboardEfficiencyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/district-predictions': {
      id: '/dashboard/district-predictions'
      path: '/district-predictions'
      fullPath: '/dashboard/district-predictions'
      preLoaderRoute: typeof DashboardDistrictPredictionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/data-transparency': {
      id: '/dashboard/data-transparency'
      path: '/data-transparency'
      fullPath: '/dashboard/data-transparency'
      preLoaderRoute: typeof DashboardDataTransparencyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/crisis': {
      id: '/dashboard/crisis'
      path: '/crisis'
      fullPath: '/dashboard/crisis'
      preLoaderRoute: typeof DashboardCrisisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/capacity': {
      id: '/dashboard/capacity'
      path: '/capacity'
      fullPath: '/dashboard/capacity'
      preLoaderRoute: typeof DashboardCapacityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bed-allocation': {
      id: '/dashboard/bed-allocation'
      path: '/bed-allocation'
      fullPath: '/dashboard/bed-allocation'
      preLoaderRoute: typeof DashboardBedAllocationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-transparency': {
      id: '/dashboard/ai-transparency'
      path: '/ai-transparency'
      fullPath: '/dashboard/ai-transparency'
      preLoaderRoute: typeof DashboardAiTransparencyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAiTransparencyRoute: typeof DashboardAiTransparencyRoute
  DashboardBedAllocationRoute: typeof DashboardBedAllocationRoute
  DashboardCapacityRoute: typeof DashboardCapacityRoute
  DashboardCrisisRoute: typeof DashboardCrisisRoute
  DashboardDataTransparencyRoute: typeof DashboardDataTransparencyRoute
  DashboardDistrictPredictionsRoute: typeof DashboardDistrictPredictionsRoute
  DashboardEfficiencyRoute: typeof DashboardEfficiencyRoute
  DashboardEmergencyRoute: typeof DashboardEmergencyRoute
  DashboardEquipmentRoute: typeof DashboardEquipmentRoute
  DashboardForecastRoute: typeof DashboardForecastRoute
  DashboardIcuOperationsRoute: typeof DashboardIcuOperationsRoute
  DashboardImpactRoute: typeof DashboardImpactRoute
  DashboardIntakeRoute: typeof DashboardIntakeRoute
  DashboardPatientFlowRoute: typeof DashboardPatientFlowRoute
  DashboardRecommendationsRoute: typeof DashboardRecommendationsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardResourceRoutingRoute: typeof DashboardResourceRoutingRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSimulationRoute: typeof DashboardSimulationRoute
  DashboardTwinRoute: typeof DashboardTwinRoute
  DashboardWorkforceRoute: typeof DashboardWorkforceRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAiTransparencyRoute: DashboardAiTransparencyRoute,
  DashboardBedAllocationRoute: DashboardBedAllocationRoute,
  DashboardCapacityRoute: DashboardCapacityRoute,
  DashboardCrisisRoute: DashboardCrisisRoute,
  DashboardDataTransparencyRoute: DashboardDataTransparencyRoute,
  DashboardDistrictPredictionsRoute: DashboardDistrictPredictionsRoute,
  DashboardEfficiencyRoute: DashboardEfficiencyRoute,
  DashboardEmergencyRoute: DashboardEmergencyRoute,
  DashboardEquipmentRoute: DashboardEquipmentRoute,
  DashboardForecastRoute: DashboardForecastRoute,
  DashboardIcuOperationsRoute: DashboardIcuOperationsRoute,
  DashboardImpactRoute: DashboardImpactRoute,
  DashboardIntakeRoute: DashboardIntakeRoute,
  DashboardPatientFlowRoute: DashboardPatientFlowRoute,
  DashboardRecommendationsRoute: DashboardRecommendationsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardResourceRoutingRoute: DashboardResourceRoutingRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSimulationRoute: DashboardSimulationRoute,
  DashboardTwinRoute: DashboardTwinRoute,
  DashboardWorkforceRoute: DashboardWorkforceRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface HospitalRouteChildren {
  HospitalAlertsRoute: typeof HospitalAlertsRoute
  HospitalAnalyticsRoute: typeof HospitalAnalyticsRoute
  HospitalAutomationRoute: typeof HospitalAutomationRoute
  HospitalBedsRoute: typeof HospitalBedsRoute
  HospitalDataRoute: typeof HospitalDataRoute
  HospitalEquipmentRoute: typeof HospitalEquipmentRoute
  HospitalForgotPasswordRoute: typeof HospitalForgotPasswordRoute
  HospitalHistoryRoute: typeof HospitalHistoryRoute
  HospitalIcuRoute: typeof HospitalIcuRoute
  HospitalLearningRoute: typeof HospitalLearningRoute
  HospitalLoginRoute: typeof HospitalLoginRoute
  HospitalOnboardingRoute: typeof HospitalOnboardingRoute
  HospitalPatientsRoute: typeof HospitalPatientsRoute
  HospitalReportsRoute: typeof HospitalReportsRoute
  HospitalSettingsRoute: typeof HospitalSettingsRoute
  HospitalSignupRoute: typeof HospitalSignupRoute
  HospitalStaffRoute: typeof HospitalStaffRoute
  HospitalIndexRoute: typeof HospitalIndexRoute
}

const HospitalRouteChildren: HospitalRouteChildren = {
  HospitalAlertsRoute: HospitalAlertsRoute,
  HospitalAnalyticsRoute: HospitalAnalyticsRoute,
  HospitalAutomationRoute: HospitalAutomationRoute,
  HospitalBedsRoute: HospitalBedsRoute,
  HospitalDataRoute: HospitalDataRoute,
  HospitalEquipmentRoute: HospitalEquipmentRoute,
  HospitalForgotPasswordRoute: HospitalForgotPasswordRoute,
  HospitalHistoryRoute: HospitalHistoryRoute,
  HospitalIcuRoute: HospitalIcuRoute,
  HospitalLearningRoute: HospitalLearningRoute,
  HospitalLoginRoute: HospitalLoginRoute,
  HospitalOnboardingRoute: HospitalOnboardingRoute,
  HospitalPatientsRoute: HospitalPatientsRoute,
  HospitalReportsRoute: HospitalReportsRoute,
  HospitalSettingsRoute: HospitalSettingsRoute,
  HospitalSignupRoute: HospitalSignupRoute,
  HospitalStaffRoute: HospitalStaffRoute,
  HospitalIndexRoute: HospitalIndexRoute,
}

const HospitalRouteWithChildren = HospitalRoute._addFileChildren(
  HospitalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  HospitalRoute: HospitalRouteWithChildren,
  PricingRoute: PricingRoute,
  SecurityRoute: SecurityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
